### ISSUE TITLE
How to use this module within the customeraccount page(s)?

### ISSUE THREAD

**Issue by jeroenalewijns** [postcode-nl/PostcodeNl_Api_Magento2#42]
Is there an option to use this module in the customer account as well? 

E.g. I can fill in the country, postcode and house number field in the http://www.aaa.bbb/customer/address/new/ page and it will return my address and city.

**Comment by JerrySmidt** [comment]
This is not currently supported but may be in a future version. Will look into this.

**Comment by aadmathijssen** [comment]
Hi, we are currently facing issues with the fact that orders contain incorrect addresses, due to the fact that address API integration is missing in the address book of the customer account pages.

Since we have started to use this module, we have faced dozens of occurrences of the following scenario:
# Customer creates an address in the address book in a wrong format (e.g. missing/duplicate house number and/or addition, or fields in the wrong order); because there is no API integration, there is no good way to prevent his.
# In the checkout, the customer chooses the address from the address book (in case there is only one address, this is even the default choice), and places the order.
# A Magento cron task tries to synchronize this order to other services, but this synchronisation fails because the address is invalid. The only resolution is to manually correct the address of the order, which in some cases is impossible without contacting the customer (e.g. when the house number is missing).

Can you please see if this can be prioritized on the backlog?

Thanks!

**Comment by JerrySmidt** [comment]
Update: this will be supported in a future version. It will take some time though because the customer address form requires an implementation that is quite different from the checkout.

**Comment by jorgb90** [comment]
Nice @JerrySmidt ! This would be a very welcome future :)

**Comment by JerrySmidt** [comment]
Address autocomplete for the customer address form has now been implemented and is available in release 3.1.8.
